---

- name: Wait for a file to exist on Windows host
  hosts: murry
  tasks:
    - name: Get the current date in specified format using PowerShell
      win_shell: |
        $date = Get-Date
        $formattedDate = $date.ToString("MM.dd.yyyy_HH:mm:ss")
        $formattedDate = $formattedDate -replace '[.:]', ''
        $formattedDate += ".txt"
        Write-Output $formattedDate
      register: result
    - name: Display formatted date
      debug:
        msg: "The formatted date is {{ result.stdout }}"
    - name: Wait for file to exist
      win_wait_for:
        path: D:\delete\{{ result.stdout }}
        state: present
        timeout: 300  # Adjust timeout as needed (in seconds)
