- name: Wait for a file to exist on Windows host
  hosts: murry
  tasks:
    - name: Get current date
      set_fact:
        current_date: "{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}"
    - name: Display current date
      debug:
        msg: "Today's date is {{ current_date }}"
    - name: Get the current date in specified format using PowerShell
      win_shell: |
        $date = Get-Date
        $formattedDate = $date.ToString("MM.dd.yyyy_HH:mm:ss")
        $formattedDate = $formattedDate -replace '[.:]', ''
        $formattedDate
      register: result
    - name: Remove carriage return and newline characters
      set_fact:
        formatted_date: "{{ result.stdout | replace('\r\n', '') | replace('\r', '') }}"
    - name: Display formatted date
      debug:
        msg: "The formatted date is {{ formatted_date }}"
    - name: Wait for file to exist
      win_wait_for:
        path: "D:\\delete\\{{ formatted_date }}"
        state: present
        timeout: 300  # Adjust timeout as needed (in seconds)
