---
- hosts: TOWER.HOME.COM
  gather_facts: no   
  tasks:
    - name: Main Block
      block: 
        - name: Execute PowerShell script
          ignore_errors: False
          register: output
          command: pwsh /home/ansible/execute.ps1 "{{ serverName }}" "{{ param1 }}" "{{ param2 }}" "{{ param3 }}" "{{ param4 }}" "{{ param5 }}" "{{ param6 }}"
      rescue:
        - name: Debug
          debug:
            msg: "Error Occured - {{output.stdout}}"
          
      
