---
- name: Get info for all services starting with 'SQL'
  hosts: win
  collections:
    - ansible.windows
  tasks:
    - name: Get service info
      win_service_info:
        name: 'SQL*'
      register: services

    - name: Output service info
      debug:
        var: service_info

    - name: Stop services starting with 'SQL'
    win_service:
      name: "{{ item.name }}"
      state: stopped
    loop: "{{ services.services }}"
