---
- name: Get info for all services starting with 'SQL'
  hosts: win
  collections:
    - ansible.windows
  tasks:
    - name: Get service info
      win_service_info:
        name: 'SQL*'
      register: service_info

    - name: Output service info
      debug:
        var: service_info
