---
- name: Stop MySQL80 service
  hosts: win
  collections:
    - ansible.windows
  vars:
      sleepsec: 10
  tasks:
    - name: Get all services starting with 'SQL'
      win_service_info:
        name: 'SQL*'
      register: services
    - name: Debug
      debug:
        var: "services"    
    - name: Pause for 10 seconds
      pause:
        seconds: "{{ sleepsec }}"   
    - name: Start MySQL80 service  
      win_shell: |
        Start-Service -Name MySQL80
