---
- name: Stop MySQL80 service
  hosts: win
  tasks:
    - name: Stop MySQL80 service
      win_service:
        name: MySQL80
        state: stopped
    - name: Start MySQL80 service  
      win_shell: |
        Start-Service -Name MySQL80
