---
- name: Get info for all services starting with 'SQL'
  hosts: windows
  tasks:
    - name: Get service info
      ansible.windows.win_service_info:
        name: 'SQL*'
      register: service_info

    - name: Output service info
      debug:
        var: service_info
