---
- name: Stop MySQL80 service
  hosts: win
  tasks:
    - name: Stop MySQL80 service
      win_service:
        name: "{{ item }}"
        state: stopped
      loop:
        - MySQL*
    - name: Start MySQL80 service  
      win_shell: |
        Start-Service -Name MySQL80
