---
- name: deploy vsftpd
  hosts: ansible1
  tasks: 
  - name: install vsftpd
    yum: name=vsftpd
  - name: enable vsftpd
    service: name=vsftpd enabled=true
  - name: Use a module from community.general collection
    community.general.ping:
      data: "Hello from tower"
